#!/usr/bin/ruby
#
# This file is part of CPEE-HISTORY.
#
# CPEE-HISTORY is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# CPEE-HISTORY is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with CPEE-HISTORY (file LICENSE in the main directory). If not, see
# <http://www.gnu.org/licenses/>.

if File.exist?(File.join(__dir__,'..','lib','cpee-history','implementation.rb'))
  require_relative File.join(__dir__,'..','lib','cpee-history','implementation')
elsif File.exist?(File.join(Dir.home,'Projects','cpee-history','lib','cpee-history','implementation.rb'))
  require_relative File.join(Dir.home, 'Projects','cpee-history','lib','cpee-history','implementation')
else
  require 'cpee-history/implementation'
end

options = {
  :host => 'localhost',
  :port => 9318,
  :secure => false,
  :base => __dir__
}

Riddl::Server.new(CPEE::History::SERVER, options) do
  accessible_description true
  cross_site_xhr true

  use CPEE::History::implementation(@riddl_opts)
end.loop!
